### ISSUE TITLE
Can't initialize multiple instances of the same contract

### ISSUE THREAD

**Issue by LuisOsta** [rapid-eth/ethers-react-system#3]
**Describe the bug**
The uniqueID won't allow for multiple instances of the same smart contract. Thus if you initialize a new version, it will override the old version. Although you can provide a uniqueID via the action creator, it is not possible via the EthersProvider. Furthermore, default uniqueID should always be unique.

**To Reproduce**
1. In the EthersProvider or action, the creator provides smart contract X
2. Add/Initialize the smart contract X again
3. Only one instance of the smart contract will appear

**Expected behavior**
The EthersProvider should allow for multiple instances of the same smart contract. The default unique ID should utilize at least part of the ethereum address in order to assure uniqueness.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 76

**Additional context**
Although you can override the uniqueID via the action creator(initContract), you can't do the same with the EthersProvider initialization.

**Comment by LuisOsta** [comment]
@KamesCG @onpaws The new code is on the dev branch. Once reviewed and confirmed we can merge it into master.

**Comment by robbiekruszynski** [comment]
@KamesCG can I clear this ticket?

**Comment by robbiekruszynski** [comment]
<3 Luis
